# Generated by Django 4.2.7 on 2023-11-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikimap', '0002_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Table',
        ),
    ]
