# Generated by Django 4.2.7 on 2023-11-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikimap', '0003_delete_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
