# Generated by Django 4.2.7 on 2023-12-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikimap', '0004_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityinfo',
            old_name='area',
            new_name='extent',
        ),
    ]
